# Challenge: Promotions

In this challenge, you'll develop codes to parse and analyze data returned from another API on Zalando such as [Promos homme (Men's Promotions)
](https://www.zalando.fr/promo-homme/) or [Promos femme (Women's Promotions)](https://www.zalando.fr/promo-femme/). The workflow is almost the same as in the guided lesson but you'll work with different data.

## Obtaining the link

Wrote your codes in the cell below to obtain the data from the API endpoint you choose. A recap of the workflow:

1. Examine the webpages and choose one that you want to work with.

1. Use Google Chrome's DevTools to inspect the XHR network requests. Find out the API endpoint that serves data to the webpage.

1. Test the API endpoint in the browser to verify its data.

1. Change the page number offset of the API URL to test if it's working.

In [1]:
# your code here
#import libraries
import json
import requests
import pandas as pd
from pandas.io.json import json_normalize


usr_agent = 'Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36'
headers = {'User-Agent' : usr_agent}

#url pour homme
url = 'https://www.zalando.fr/api/catalog/articles?categories=promo-homme&limit=84&offset=84&sort=popularity'

#obtain webpage
response = requests.get(url,headers = headers)
results = response.json()
results


flattened_data = json_normalize(results)

flattened_data1 = json_normalize(flattened_data.articles[0])
flattened_data1.head(4)

C:\Users\rsher\anaconda3\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
C:\Users\rsher\anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

,sku,name,url_key,media,brand_name,is_premium,flags,product_group,delivery_promises,price.original,price.promotional,price.has_different_prices,price.has_different_original_prices,price.has_different_promotional_prices,price.has_discount_on_selected_sizes_only,outfits
0,NI122F04P-Q11,ALUMNI - Short - black/white,nike-sportswear-alumni-short-blackwhite-ni122f...,[{'path': 'NI/12/2F/04/PQ/11/NI122F04P-Q11@8.j...,Nike Sportswear,False,"[{'key': 'discountRate', 'value': '-30%', 'tra...",clothing,[],"49,95 €","34,95 €",False,False,False,False,NaN
1,IJ023C001-K11,CUBA CADEN - Short en jean - blau,indicode-jeans-cuba-short-en-jean-ij023c001-k11,[{'path': 'IJ/02/3C/00/1K/11/IJ023C001-K11@13....,INDICODE JEANS,False,"[{'key': 'discountRate', 'value': '-8%', 'trac...",clothing,[],"39,95 €","36,95 €",False,False,False,False,NaN
2,LA222D01Y-K23,T-shirt basique - blue,lacoste-t-shirt-basique-blue-la222d01y-k23,[{'path': 'LA/22/2D/01/YK/23/LA222D01Y-K23@13....,Lacoste,False,"[{'key': 'discountRate', 'value': 'Jusqu’à -15...",clothing,[],"38,95 €","33,05 €",True,False,True,False,NaN
3,AD122O0AO-K17,3 STRIPES TEE - T-shirt imprimé - clesky,adidas-originals-3-stripes-tee-t-shirt-imprime...,[{'path': 'AD/12/2O/0A/OK/17/AD122O0AO-K17@7.j...,adidas Originals,False,"[{'key': 'discountRate', 'value': '-10%', 'tra...",clothing,[],"29,95 €","26,95 €",False,False,False,False,NaN

## Reading the data

In the next cell, use Python to obtain data from the API endpoint you chose in the previous step. Workflow:

1. Import libraries.

1. Define the initial API endpoint URL.

1. Make request to obtain data of the 1st page. Flatten the data and store it in an empty object variable.

1. Find out the total page count in the 1st page data.

1. Use a FOR loop to make requests for the additional pages from 2 to page count. Append the data of each additional page to the flatterned data object.

1. Print and review the data you obtained.

In [ ]:
# your code here

# Get the total number of pages
import json
import requests
import pandas as pd
from pandas.io.json import json_normalize
total_pages=results['pagination']['page_count']
usr_agent = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.141 Safari/537.36'
headers = {'User-Agent' : usr_agent}


# Your code
df=pd.DataFrame()
for i in range(total_pages):
    k=84*i
    url=f'https://www.zalando.fr/api/catalog/articles?categories=promo-homme&limit=84&offset={k}&sort=popularity'
    response = requests.get(url, headers = headers)
    results = response.json()
    flattened_data = json_normalize(results)
    flattened_data1 = json_normalize(flattened_data.articles[0])
    flattened_data1=flattened_data1.set_index('sku')
    df = df.append(flattened_data1)
    
df.head(1)

C:\Users\rsher\anaconda3\lib\site-packages\ipykernel_launcher.py:20: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
C:\Users\rsher\anaconda3\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

## Bonus

Extract the following information from the data:

* The trending brand.

* The product(s) with the highest discount.

* The sum of discounts of all goods (sum_discounted_prices divided by sum_original_prices).

In [ ]:
# Trending brand
df.brand_name.value_counts().index[0]

In [ ]:
# Highest discount
df['price.original']=df['price.original'].str.extract('(\d*,\d*)')
df['price.promotional']=df['price.promotional'].str.extract('(\d*,\d*)')

df['price.original'] = [x.replace(',', '.') for x in df['price.original']]
df['price.promotional'] = [x.replace(',', '.') for x in df['price.promotional']]
df['discount_amount']=df['price.original'].astype(float)-df['price.promotional'].astype(float)
df1=df.copy()
total_disc=df1.groupby(['brand_name']).sum().discount_amount
total_disc.sort_values(ascending=False).index[0]

In [ ]:
#Sum of discounts
total_disc[total_disc!=0]